# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [61]:
import torch

In [62]:
import torch
print(torch.__version__)


2.9.0+cpu


Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
tensor = torch.arange(0, 10)
print(tensor)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [64]:
print("тип элементов:", tensor.dtype)
print("размер:", tensor.shape)
print("количество размерностей:", tensor.dim())


тип элементов: torch.int64
размер: torch.Size([10])
количество размерностей: 1


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [65]:
first_part = my_tensor[:5]
print("первые 5:", first_part)

second_part = my_tensor[5:]
print("последние 5:", second_part)


первые 5: tensor([0, 1, 2, 3, 4])
последние 5: tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [66]:
ones_matrix = torch.ones(3, 4)
print(ones_matrix)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [67]:
true_matrix = torch.ones(5, 2, dtype=torch.bool)
print(true_matrix)



tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])


Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [68]:
step_tensor = torch.arange(1, 15.5, 0.5)
print(step_tensor)


tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000])


Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [69]:
uniform_tensor = torch.linspace(1, 10, 20)
print(uniform_tensor)


tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])


Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [70]:
random_tensor = torch.rand(4, 3)
print(random_tensor)


tensor([[0.0328, 0.4438, 0.9886],
        [0.9346, 0.2088, 0.3125],
        [0.4374, 0.7942, 0.5780],
        [0.6541, 0.8180, 0.4696]])


Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [71]:
grades = torch.randint(3, 6, (100,))
print("первые 10 оценок:", grades[:10])


первые 10 оценок: tensor([3, 4, 4, 4, 3, 3, 4, 3, 5, 5])


Задание 11. Для тензора "школьных оценок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [72]:
print("минимальная оценка:", grades.min())
print("максимальная оценка:", grades.max())
print("средний балл:", grades.float().mean())


минимальная оценка: tensor(3)
максимальная оценка: tensor(5)
средний балл: tensor(4.1200)


Задание 12. Создайте создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [73]:
mask = torch.zeros(100, dtype=torch.bool)
mask[:5] = True
mask[-5:] = True
print("маска (первые 10 элементов):", mask[:10])


маска (первые 10 элементов): tensor([ True,  True,  True,  True,  True, False, False, False, False, False])


Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [74]:
filtered_grades = grades[mask]
print("отфильтрованные оценки:", filtered_grades)


отфильтрованные оценки: tensor([3, 4, 4, 4, 3, 4, 4, 4, 4, 3])


Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [75]:
fives_mask = grades == 5
print("сколько пятёрок:", fives_mask.sum())


сколько пятёрок: tensor(42)


Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.


In [76]:
only_fives = grades[grades == 5]
print("все пятёрки:", only_fives)


все пятёрки: tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])


Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [77]:
grades_matrix = grades.reshape(5, 20)
print("размер после преобразования:", grades_matrix.shape)


размер после преобразования: torch.Size([5, 20])


Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [78]:
a = torch.arange(2, 12).reshape(2, -1)
b = torch.ones(10).reshape(2, -1)

vertical_stack = torch.cat([a, b], dim=0)

print("Тензор a (2x5):\n", a)
print("\nТензор b (2x5):\n", b)
print("\nРезультат вертикальной стыковки (4x5):\n", vertical_stack)
print("\nРазмер результата:", vertical_stack.shape)  # Должно быть torch.Size([4, 5])

Тензор a (2x5):
 tensor([[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11]])

Тензор b (2x5):
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Результат вертикальной стыковки (4x5):
 tensor([[ 2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])

Размер результата: torch.Size([4, 5])


Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $2 \times 10$.

In [79]:
a = torch.arange(2, 10, 2).reshape(2, -1)
b = torch.ones(10).reshape(2, -1)

horizontal_stack = torch.cat([a, b], dim=1)
print("размер после горизонтальной стыковки:", horizontal_stack.shape)

размер после горизонтальной стыковки: torch.Size([2, 7])


Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [80]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

condition = (a >= 5) & (a <= 10)
result = a[condition]
print("элементы от 5 до 10:", result)

элементы от 5 до 10: tensor([ 6,  9, 10])


Задание 20. Вывести первую строку матрицы из задания 18.

In [81]:
first_row = horizontal_stack[0, :]
print("первая строка:", first_row)

первая строка: tensor([2., 4., 1., 1., 1., 1., 1.])


Задание 21. Вывести последний столбец матрицы из задания 17.

In [82]:
last_col = vertical_stack[:, -1]
print("последний столбец:", last_col)

последний столбец: tensor([ 6., 11.,  1.,  1.])


Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [83]:
center = vertical_stack[1:3, 1:4]
print("центральная часть:")
print(center)

центральная часть:
tensor([[ 8.,  9., 10.],
        [ 1.,  1.,  1.]])


Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [84]:
min_val = vertical_stack.min()
new_row = torch.full((1, vertical_stack.shape[1]), min_val)
new_tensor = torch.cat([new_row, vertical_stack], dim=0)
print("новый тензор с добавленной строкой:")
print(new_tensor)

новый тензор с добавленной строкой:
tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])


Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [85]:
sqrt_tensor = torch.sqrt(new_tensor.float())
print("квадратные корни:")
print(sqrt_tensor)

квадратные корни:
tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 1.7321, 2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000, 3.1623, 3.3166],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])


Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [86]:
result = horizontal_stack.clone()
mask = (result % 2 == 0) | (result % 3 == 0)
result[mask] = 1
print("после замены:")
print(result)

после замены:
tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])
