# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [1]:
import torch

In [2]:
import torch
print(torch.__version__)


2.10.0+cpu


Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
tensor = torch.arange(10)
print(tensor)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [4]:
print(tensor.dtype)
print(tensor.shape)
print(tensor.dim())

torch.int64
torch.Size([10])
1


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [5]:
left = tensor[:5]
right = tensor[5:]
print(left)
print(right)


tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [6]:
ones_matrix = torch.ones(3, 4)
print(ones_matrix)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [7]:
bool_matrix = torch.ones(5, 2, dtype=torch.bool)
print(bool_matrix)


tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])


Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [8]:
step_tensor = torch.arange(1, 15.5, 0.5)
print(step_tensor)

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000])


Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [9]:
lin_tensor = torch.linspace(1, 10, 20)
print(lin_tensor)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])


Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [10]:
rand_tensor = torch.rand(4, 3)
print(rand_tensor)


tensor([[0.0486, 0.5035, 0.3928],
        [0.2021, 0.9686, 0.8040],
        [0.2660, 0.3961, 0.0517],
        [0.8455, 0.8576, 0.7637]])


Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [11]:
grades = torch.randint(3, 6, (100,))
print(grades[:10])


tensor([4, 5, 3, 4, 5, 5, 5, 3, 4, 3])


Задание 11. Для тензора "школьных отенок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [12]:
print(grades.min())
print(grades.max())
print(grades.float().mean())


tensor(3)
tensor(5)
tensor(3.9300)


Задание 12. Создайте создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [13]:
mask = torch.zeros(100, dtype=torch.bool)
mask[:5] = True
mask[-5:] = True
print(mask[:10])

tensor([ True,  True,  True,  True,  True, False, False, False, False, False])


Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [14]:
filtered = grades[mask]
print(filtered)


tensor([4, 5, 3, 4, 5, 5, 5, 3, 4, 3])


Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [15]:
fives_mask = grades == 5
print(fives_mask.sum())

tensor(32)


Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.


In [16]:
only_fives = grades[grades == 5]
print(only_fives)


tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5])


Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [17]:
grades_2d = grades.reshape(5, 20)
print(grades_2d.shape)


torch.Size([5, 20])


Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [18]:
a = torch.arange(2, 12).reshape(2, -1)
b = torch.ones(10).reshape(2, -1)
vstack = torch.cat([a, b], dim=0)
print(vstack.shape)


torch.Size([4, 5])


Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $2 \times 10$.

In [19]:
hstack = torch.cat([a, b], dim=1)
print(hstack.shape)

torch.Size([2, 10])


Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [20]:
a2 = torch.tensor([2, 6, 1, 9, 10, 3, 27])
result = a2[(a2 >= 5) & (a2 <= 10)]
print(result)

tensor([ 6,  9, 10])


Задание 20. Вывести первую строку матрицы из задания 18.

In [21]:
print(hstack[0, :])

tensor([2., 3., 4., 5., 6., 1., 1., 1., 1., 1.])


Задание 21. Вывести последний столбец матрицы из задания 17.

In [22]:
print(vstack[:, -1])

tensor([ 6., 11.,  1.,  1.])


Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [23]:
center = vstack[1:3, 1:4]
print(center)

tensor([[ 8.,  9., 10.],
        [ 1.,  1.,  1.]])


Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [24]:
min_val = vstack.min()
new_row = torch.full((1, vstack.shape[1]), min_val)
new_tensor = torch.cat([new_row, vstack], dim=0)
print(new_tensor)


tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])


Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [25]:
sqrt_tensor = torch.sqrt(new_tensor.float())
print(sqrt_tensor)

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 1.7321, 2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000, 3.1623, 3.3166],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])


Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [26]:
modified = hstack.clone()
modified[(modified % 2 == 0) | (modified % 3 == 0)] = 1
print(modified)

tensor([[ 1.,  1.,  1.,  5.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 7.,  1.,  1.,  1., 11.,  1.,  1.,  1.,  1.,  1.]])
